name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SpotifyClientId: test_client_id
      SpotifyClientSecret: test_client_secret
      VUE_APP_SPOTIFY_CLIENT_ID: test_client_id
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test:unit
  coverage:
    steps:
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 828a156fb6438c3de0efe354ac5fe7043c0e4687151099c699f0ba51c508ea2b
        with:
          coverageCommand: yarn test:unit --coverage
          coverageLocations: |
            ${{github.workspace}}/*.lcov:lcov
